apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-master-sa
  namespace: ai-agents
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-master-role
  namespace: ai-agents
rules:
  - apiGroups: [""]
    resources: ["pods","services","configmaps"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-master-rb
  namespace: ai-agents
subjects:
  - kind: ServiceAccount
    name: agent-master-sa
roleRef:
  kind: Role
  name: agent-master-role
  apiGroup: rbac.authorization.k8s.io